name: Firebase CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checando branch
        uses: actions/checkout@master

      - name: Firebase deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
